// <auto-generated />
using System;
using FiloYenile.Veri;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiloYenile.Migrations
{
    [DbContext(typeof(FiloDbContext))]
    [Migration("20260824171308_IlkSqliteVeritabani")]
    partial class IlkSqliteVeritabani
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FiloYenile.Modeller.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArizaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GuncelDeger")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilometre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelYili")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YakitTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YillikBakimMaliyeti")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YillikYakitMaliyeti")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Araclar");
                });
#pragma warning restore 612, 618
        }
    }
}
